### ISSUE TITLE
Please upload releases to pypi

### ISSUE THREAD

**Issue by yarikoptic** [cbinyu/bidsphysio#1]
It is really easy as long as there is proper setup.py/.cfg! see https://packaging.python.org/tutorials/packaging-projects/ for all gory details, but in general it is something like
```
python setup.py sdist
twine upload dist/<tarball>
```
you could even generate .whl's but I think best to start "basic" ;)

**Comment by pvelasco** [comment]
Done!

You can install it now from pypi:

```
pip install bidsphysio
```

Please note that you need to install `numpy` first, otherwise it gives an error that `bioread` needs `numpy` (even though `numpy` is a `install_requirement` for both `bidsphysio` and `bioread`).  Do you know a way to force `pip` to install first `numpy` and only then attempt to install `bioread`?

**Comment by yarikoptic** [comment]
quick one: I don't know about `install_requirement`... I know `install_requires`

**Comment by pvelasco** [comment]
> quick one: I don't know about `install_requirement`... I know `install_requires`

That's what I meant: `install_requires`.

**Comment by pvelasco** [comment]
I think the problem is [`bioread`'s setup](https://github.com/uwmadison-chm/bioread/blob/master/setup.py).
Their call to `setup()` reads the file `bioread/_metadata.py`, so `bioread/__init__.py` will be run, which imports `bioread/reader.py` which, in turn, imports `numpy`.  So, basically, it looks like you need `numpy` to run their `setup`.
Anyway, you can install `bidsphysio` by running:
```
pip install numpy
pip install bidsphysio
```

**Comment by yarikoptic** [comment]
good troubleshooting! There are some newish ways to define additional setup dependencies, but I think the best would be for `bioread` to resolve that issue -- numpy really shouldn't be needed at setup time.  could you file an issue?  and since there is nothing really to solve at bidsphysio level and there is a release on pypi -- closing this particular issue.
