### ISSUE TITLE
physio2bidsphysio introducing NaNs

### ISSUE THREAD

**Issue by alexsayal** [cbinyu/bidsphysio#7]
Hello,

I am using bidsphysio (v21.6.24) to convert _PULS.log and _RESP.log files to BIDS.

For some reason, the script is adding NaNs to the output files, that I do not see on the original .log files.

[physio_files.zip](https://github.com/cbinyu/bidsphysio/files/7580360/physio_files.zip)

Could you please help me check what is happening?

This is the call I am using:
```
physio2bidsphysio --infiles Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_PULS.log Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_RESP.log Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_Info.log --bidsprefix sub-01_task-AA_acq-0500_run-01
```

Thank you in advance,

**Comment by pvelasco** [comment]
Hi @alexsayal,

`dcm2bids` inserts NaNs where there are data missing.
https://github.com/cbinyu/bidsphysio/blob/4c308a41a72864428e8dbd56534e61d8f1a42328/bidsphysio.dcm2bids/bidsphysio/dcm2bids/dcm2bidsphysio.py#L190-L191

BIDS physio files don't have the sampling time stored in them, but rather rely on the `StartTime` and `SamplingFrequency` to determine the time a specific sample was recorded (https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/06-physiological-and-other-continuous-recordings.html). Therefore, you need to have a value per timepoint. Siemens `.log` files, for some reason, miss some sample points (I'm not sure why, maybe when it detects a peak), and `dcm2bids` needs to write something for that timepoint; I chose to write NaNs, so that you can easily replace it with whatever value you want.

For example, for the cardiac recording, the first `nan` in the output file is between samples `2060.0000` and `2030.0000`. If you look in the original `Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_PULS.log`, you will see that the difference in `ACQ_TIME_TICS` is 4, while normally it is 2, indicating there is a missing recording. (Note, one "tic" corresponds to 2.5ms.)

Do you have any suggestion for what value/string to introduce when there is a missing sample?

**Comment by alexsayal** [comment]
Hello @pvelasco ,

Thank you for that clarification. I will check what is the best option to deal with that missing data, but probably it will need to be interpolated.

In either case, I agree with the approach of inserting NaNs at this stage, since that is closest to what is on the siemens file.

All the best,

**Comment by pvelasco** [comment]
Closing it for now. Feel free to reopen if needed.
